openapi: 3.1.0
info:
  title: Financial Instrument Sample Polymorph
  version: 1.0.0
  description: 'This is the description'
  contact:
    email: openwealth@synpulse.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Sample Server URL
    url: https://openwealth.ch/
externalDocs:
  description: Find out more about OpenWealth API specifications.
  url: https://openwealth.ch/
paths:
  /financial-instruments:
    get:
      responses:
        '200':
          description: gets list of instruments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'FinancialInstrument.yaml'
              examples:
                Cash:
                  summary: A foo example
                  value: { 'name': 'Swiss Franks', 'currency': 'CHF' }
                Equity:
                  summary: A foo example
                  value:
                    {
                      'name': 'Apple Inc.',
                      'identificationList':
                        [{ 'type': 'isin', 'identifier': 'US0378331005' }],
                    }
                Bond:
                  summary: A bar example
                  value:
                    {
                      'name': '0,5% 18/32 Swiss Gov.',
                      'maturityDate': '2032-06-27',
                      'identificationList':
                        [{ 'type': 'isin', 'identifier': 'CH0344958688' }],
                    }
components: {}
