name: Bundle and lint workflow
# description: Check specifications for SFTI's openapi rules.
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled] # Trigger on PR actions like opening or updating a PR
    branches:
      - main # Only triggers for pull requests targeting the main branch

env:
  REDOCLY_VERSION: '1.25.3'

permissions:
  contents: write
  pull-requests: write

jobs:
  bundle-and-lint-api:
    if: contains(github.event.pull_request.labels.*.name, 'instrument')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Checkout the head branch of the PR

      - name: Set API of subject from label
        if: contains(github.event.pull_request.labels.*.name, 'instrument')
        run: echo "API_NAME=instrument" >> $GITHUB_ENV

      - name: Get Pull Request Labels and set variables
        id: var
        run: |
          apiFile="${API_NAME^}/${API_NAME}API.yaml"
          apiBundledFile="${API_NAME^}/build/${API_NAME}API.yaml"
          echo "API_FILE"=$apiFile >> $GITHUB_OUTPUT
          echo "API_BUNDLED_FILE"=$apiBundledFile >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # Install Redocly CLI
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      # Run the Redocly bundle command
      - name: Bundle API docs
        run: redocly bundle ${{ steps.var.outputs.API_FILE }} --output ${{ steps.var.outputs.API_BUNDLED_FILE }} # Adjust the paths as needed

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Check if there are changes to commit
      - name: Commit changes
        run: |
          git add ${{ steps.var.outputs.API_BUNDLED_FILE }}
          git commit -m "Update bundled API file" || echo "No changes to commit"

      # Push the changes back to the head branch
      - name: Push changes
        run: |
          git push origin HEAD:${{ github.head_ref }}  # Push to the branch that triggered the workflow

      # Run the Redocly lint command
      - name: Run Redocly lint
        run: redocly lint --config=.github/redocly.yaml --format=stylish ${{ steps.var.outputs.API_BUNDLED_FILE }}
