name: Bundle and lint workflow
# description: Check specifications for SFTI's openapi rules.
on:
  push:
    branches-ignore:
      - main # This will ignore the main branch

env:
  REDOCLY_VERSION: '1.25.3'

permissions:
  contents: write

jobs:
  bundle-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Validate branch name convention parameters
        id: api_in_scope_check
        run: |
          apiInScopeRegex="instrument-"
          if [[ ! "${{ github.ref }}" =~ $apiInScopeRegex ]]; then
            echo "Branch name does not match naming convention. Branch name must start with 'instrument-'."
            exit 0
          fi

      - name: Extract variables for Release action # Adjust names only here
        id: var
        run: |
          apiName=$(echo "${{ github.ref }}" | grep -o 'instrument-'  | grep -o 'instrument')
          echo "Head branch: ${{ github.ref }}"
          echo "Api name: $apiName"
          apiFile="${apiName^}/${apiName}API.yaml"
          apiBundledFile="${apiName^}/build/${apiName}API.yaml"
          echo "API_NAME"=$apiName >> $GITHUB_OUTPUT
          echo "API_FILE"=$apiFile >> $GITHUB_OUTPUT
          echo "API_BUNDLED_FILE"=$apiBundledFile >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # Install Redocly CLI
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      # Run the Redocly bundle command
      - name: Bundle API docs
        run: redocly bundle ${{ steps.var.outputs.API_FILE }} --output ${{ steps.var.outputs.API_BUNDLED_FILE }} # Adjust the paths as needed

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Check if there are changes to commit
      - name: Commit changes
        run: |
          git add ${{ steps.var.outputs.API_BUNDLED_FILE }}
          git commit -m "Update bundled API file" || echo "No changes to commit"

      # Push the changes back to the head branch
      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref }}  # Push to the branch that triggered the workflow
