name: OpenAPI lint workflow
# description: Check specifications for SFTI's openapi rules.
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      apiName:
        type: string
        default: 'instrument'
        description: 'Files to be linted (list of files sperated by a whitespace). Default: *.yaml'

env:
  REDOCLY_VERSION: '1.25.3'

jobs:
  lint-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Extract variables for Release action # Adjust names only here
        id: var
        run: |
          apiName=${{ github.event.inputs.apiName }}
          apiFile="${apiName^}/build/${apiName}API.yaml"
          echo "API_NAME"=$apiName >> $GITHUB_OUTPUT
          echo "API_FILE"=$apiFile >> $GITHUB_OUTPUT

      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Run Redocly lint
        run: redocly lint --config=./.github/redocly.yaml --format=summary ${{ steps.var.outputs.API_FILE }}
